_target_: models.base_model.BaseModel

net:
  _target_: archs.PSuperModel.PSuperModel
  initial_weights: /kaggle/working/Realtime-Targeted-Speech-Enhancement/rttse/archs/Denoiser_init_ckpt.th
  strict: false
  reference_embedding: 192
  target_embedding: 768
  speech_enhancer:
    _target_: archs.PDenoiser.PDenoiser
    reference_embedding: 192
    chin: 1
    chout: 1
    hidden: 48
    max_hidden: 10000
    causal: true
    glu: true
    depth: 5
    kernel_size: 8
    stride: 4
    normalize: true
    resample: 4
    growth: 2
    rescale: 0.1
    freeze_encoder: false
    freeze_decoder: false
    freeze_lstm: false
  speech_embedder:
    _target_: embedders.ECAPATDNN.ECAPATDNN
    
