# compile:
  # torch.compile args

acoustics:
  n_fft: 512
  win_length: 512
  sr: 16000
  hop_length: 256

train:  
  optim:
    _target_: torch.optim.Adam
    lr: 1e-3

  losses:
    l1:
      _target_: torch.nn.MSELoss
      reduction: mean


val:
  metrics:
    pesq_wb:
      _target_: torchmetrics.audio.pesq.PerceptualEvaluationSpeechQuality
      fs: 16000
      mode: wb

    pesq_nb:
      _target_: torchmetrics.audio.pesq.PerceptualEvaluationSpeechQuality
      fs: 16000
      mode: nb
      
    stoi:
      _target_: torchmetrics.audio.stoi.ShortTimeObjectiveIntelligibility
      fs: 16000