train:
  optim:
    _target_: torch.optim.Adam
    lr: 1e-4
    weight_decay: 0.0

  scheduler:
    _target_: torch.optim.lr_scheduler.CosineAnnealingLR
    T_max: 100000
    eta_min: 1e-6


  losses:
    loss:
      _target_: loss.waveformer_loss.WaveformerLoss
    l1:
      _target_: torch.nn.L1Loss
      reduction: mean
      

val:
  metrics:
    # pesq_wb:
    #   _target_: torchmetrics.audio.pesq.PerceptualEvaluationSpeechQuality
    #   fs: 44100
    #   mode: wb

    # pesq_nb:
    #   _target_: torchmetrics.audio.pesq.PerceptualEvaluationSpeechQuality
    #   fs: 44100
    #   mode: nb

    # stoi:
    #   _target_: torchmetrics.audio.stoi.ShortTimeObjectiveIntelligibility
    #   fs: 44100

    # si_snr:
    #   _target_: torchmetrics.audio.ScaleInvariantSignalNoiseRatio
    
    DNSMOS:
      _target_: metrics.dnsmos_local.DNSMOSScore
      fs: 44100
      personalized_MOS: True
