train:
  optim:
    _target_: torch.optim.Adam
    lr: 1e-4
    weight_decay: 0.0

  scheduler:
    _target_: torch.optim.lr_scheduler.CosineAnnealingLR
    T_max: 100000
    eta_min: 1e-6

  losses:
    l1:
      _target_: torch.nn.L1Loss
      reduction: mean

    mrstft:
      _target_: loss.stft_loss.MultiResolutionSTFTLoss
      sc_lambda: 0.5
      mag_lambda: 0.5
      band: full
      hop_sizes: [50, 120, 240]
      win_lengths: [240, 600, 1200]
      fft_sizes: [512, 1024, 2048]
      

val:
  metrics:
    # pesq_wb:
    #   _target_: torchmetrics.audio.pesq.PerceptualEvaluationSpeechQuality
    #   fs: 44100
    #   mode: wb

    # pesq_nb:
    #   _target_: torchmetrics.audio.pesq.PerceptualEvaluationSpeechQuality
    #   fs: 44100
    #   mode: nb

    # stoi:
    #   _target_: torchmetrics.audio.stoi.ShortTimeObjectiveIntelligibility
    #   fs: 44100

    # si_snr:
    #   _target_: torchmetrics.audio.ScaleInvariantSignalNoiseRatio
    
    DNSMOS:
      _target_: metrics.dnsmos_local.DNSMOSScore
      fs: 44100
      personalized_MOS: True
