name: CleanUNet
hydra:
  job:
    name: ${name}
  run:
    dir: experiments/${name}/${now:%Y-%m-%d_%H-%M-%S}

logger:
  wandb:
    project: 
    resume_id:

defaults:
- data: CleanUNetDataSet
- model: CleanUNet
- training: CleanUNet_training
- trainer: CleanUNet_trainer



