name: CleanUNet
hydra:
  job:
    name: ${name}
  run:
    dir: experiments/${name}/${now:%Y-%m-%d_%H-%M-%S}

logger:
  use_tb_logger:
  wandb:
    project: 
    resume_id:
    group:

defaults:
- data: PDNSDataSet
- model: WaveTita
- training: WaveTita_training
- trainer: trainer



