name: stream
hydra:
  job:
    name: ${name}
  run:
    dir: results/${name}/${now:%Y-%m-%d_%H-%M-%S}

logger:
  use_tb_logger: True

streaming:
  in_device:
  out_device: "CABLE Input"
  reference_audio:
  fs: 16000
  dry: 0.04
  num_frames: 2
  num_threads: 2
  compressor: True
  device: cpu

speech_embedder:
  _target_: embedders.TitaNet.TitaNet

defaults:
- model: PDenoiser