name: CleanUNet
hydra:
  job:
    name: ${name}
  run:
    dir: results/${name}/${now:%Y-%m-%d_%H-%M-%S}

logger:
  use_tb_logger: True


defaults:
- data: random_data
- model: simpleAE
- testing: testing